BGC Tools: BGC.Utility.IdManager Class Reference
BGC.Utility.IdManager Class Reference
Public Member Functions
void Reset ()
int GetId ()
Private Attributes
int count = -1
Detailed Description
Definition at line 3 of file IdManager.cs.
Member Function Documentation
int BGC.Utility.IdManager.GetId () inline
Definition at line 12 of file IdManager.cs.
Referenced by BGC.Utility.StaticIdManager.GetId(), and BGC.Utility.StopWatch.StartTimer().
         {
             ++count;
             return count;
         }
void BGC.Utility.IdManager.Reset () inline
Definition at line 7 of file IdManager.cs.
Referenced by BGC.Utility.StaticIdManager.Reset().
         {
             count = -1;
         }
Field Documentation
int BGC.Utility.IdManager.count = -1 private
Definition at line 5 of file IdManager.cs.
The documentation for this class was generated from the following file:
Utility/IdManager.cs