BGC Tools: LightJson.JsonArray Class Reference
LightJson.JsonArray Class Reference
Represents an ordered collection of JsonValues.
Data Structures
class JsonArrayDebugView
Public Member Functions
JsonArray ()
Initializes a new instance of JsonArray.
JsonArray (params JsonValue[] values)
Initializes a new instance of JsonArray, adding the given values to the collection.
JsonArray Add (JsonValue value)
Adds the given value to this collection.
JsonArray Insert (int index, JsonValue value)
Inserts the given value at the given index in this collection.
JsonArray Remove (int index)
Removes the value at the given index.
JsonArray Clear ()
Clears the contents of this collection.
bool Contains (JsonValue item)
Determines whether the given item is in the JsonArray.
int IndexOf (JsonValue item)
Determines the index of the given item in this JsonArray.
IEnumerator< JsonValue > GetEnumerator ()
Returns an enumerator that iterates through the collection.
override string ToString ()
Returns a JSON string representing the state of the array.
string ToString (bool pretty)
Returns a JSON string representing the state of the array.
Properties
int Count [get]
Gets the number of values in this collection.
JsonValue this[int index] [get, set]
Gets or sets the value at the given index.
Private Member Functions
System.Collections.IEnumerator System.Collections.IEnumerable. GetEnumerator ()
Returns an enumerator that iterates through the collection.
Private Attributes
IList< JsonValue > items
Detailed Description
Represents an ordered collection of JsonValues.
Definition at line 13 of file JsonArray.cs.
Constructor & Destructor Documentation
LightJson.JsonArray.JsonArray () inline
Initializes a new instance of JsonArray.
Definition at line 57 of file JsonArray.cs.
         {
             this.items = new List<JsonValue>();
         }
LightJson.JsonArray.JsonArray (params JsonValue[] values) inline
Initializes a new instance of JsonArray, adding the given values to the collection.
Parameters
values The values to be added to this collection.
Definition at line 66 of file JsonArray.cs.
                                                     : this()
         {
             foreach (var value in values)
             {
                 this.items.Add(value);
             }
         }
Member Function Documentation
JsonArray LightJson.JsonArray.Add (JsonValue value) inline
Adds the given value to this collection.
Parameters
value The value to be added.
Returns
Returns this collection.
Definition at line 79 of file JsonArray.cs.
References LightJson.JsonArray.Add().
Referenced by LightJson.JsonArray.Add(), BGC.Extensions.JsonExtensions.ConvertToJsonArray< T >(), and LightJson.Serialization.JsonReader.ReadArray().
         {
             this.items.Add(value);
             return this;
         }
JsonArray LightJson.JsonArray.Clear () inline
Clears the contents of this collection.
Returns
Returns this collection.
Definition at line 112 of file JsonArray.cs.
References LightJson.JsonArray.Clear().
Referenced by LightJson.JsonArray.Clear().
         {
             this.items.Clear();
             return this;
         }
bool LightJson.JsonArray.Contains (JsonValue item) inline
Determines whether the given item is in the JsonArray.
Parameters
item The item to locate in the JsonArray.
Returns
Returns true if the item is found; otherwise, false.
Definition at line 123 of file JsonArray.cs.
         {
             return this.items.Contains(item);
         }
IEnumerator<JsonValue> LightJson.JsonArray.GetEnumerator () inline
Returns an enumerator that iterates through the collection.
Definition at line 141 of file JsonArray.cs.
Referenced by LightJson.JsonArray.GetEnumerator(), and LightJson.Serialization.JsonWriter.Render().
         {
             return this.items.GetEnumerator();
         }
System.Collections.IEnumerator System.Collections.IEnumerable. LightJson.JsonArray.GetEnumerator () inline private
Returns an enumerator that iterates through the collection.
Definition at line 149 of file JsonArray.cs.
References LightJson.JsonArray.GetEnumerator().
         {
             return this.GetEnumerator();
         }
int LightJson.JsonArray.IndexOf (JsonValue item) inline
Determines the index of the given item in this JsonArray.
Parameters
item The item to locate in this JsonArray.
Returns
The index of the item, if found. Otherwise, returns -1.
Definition at line 133 of file JsonArray.cs.
         {
             return this.items.IndexOf(item);
         }
JsonArray LightJson.JsonArray.Insert (int index, JsonValue value) inline
Inserts the given value at the given index in this collection.
Parameters
index The index where the given value will be inserted.
value The value to be inserted into this collection.
Returns
Returns this collection.
Definition at line 91 of file JsonArray.cs.
References LightJson.JsonArray.Insert().
Referenced by LightJson.JsonArray.Insert().
         {
             this.items.Insert(index, value);
             return this;
         }
JsonArray LightJson.JsonArray.Remove (int index) inline
Removes the value at the given index.
Parameters
index The index of the value to be removed.
Returns
Return this collection.
Definition at line 102 of file JsonArray.cs.
         {
             this.items.RemoveAt(index);
             return this;
         }
override string LightJson.JsonArray.ToString () inline
Returns a JSON string representing the state of the array.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Definition at line 161 of file JsonArray.cs.
         {
             return ToString(false);
         }
string LightJson.JsonArray.ToString (bool pretty) inline
Returns a JSON string representing the state of the array.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Parameters
pretty Indicates whether the resulting string should be formatted for human-readability.
Definition at line 176 of file JsonArray.cs.
         {
             using (var writer = new JsonWriter(pretty))
             {
                 return writer.Serialize(this);
             }
         }
Field Documentation
IList<JsonValue> LightJson.JsonArray.items private
Definition at line 15 of file JsonArray.cs.
Property Documentation
int LightJson.JsonArray.Count get
Gets the number of values in this collection.
Definition at line 21 of file JsonArray.cs.
JsonValue LightJson.JsonArray.this[int index] get set
Gets or sets the value at the given index.
Parameters
index The zero-based index of the value to get or set.
The getter will return JsonValue.Null if the given index is out of range.
Definition at line 36 of file JsonArray.cs.
The documentation for this class was generated from the following file:
LightJSON/JsonArray.cs