BGC Tools: LightJson.Serialization.JsonReader Class Reference
LightJson.Serialization.JsonReader Class Reference
Represents a reader that can read JsonValues.
Static Public Member Functions
static JsonValue Parse (TextReader reader)
Creates a JsonValue by using the given TextReader.
static JsonValue Parse (string source)
Creates a JsonValue by reader the JSON message in the given string.
static JsonValue ParseFile (string path)
Creates a JsonValue by reading the given file.
Private Member Functions
JsonReader (TextReader reader)
string ReadJsonKey ()
JsonValue ReadJsonValue ()
JsonValue ReadNull ()
JsonValue ReadBoolean ()
void ReadDigits (StringBuilder builder)
JsonValue ReadNumber ()
string ReadString ()
int ReadHexDigit ()
char ReadUnicodeLiteral ()
JsonObject ReadObject ()
JsonObject ReadObject (JsonObject jsonObject)
JsonArray ReadArray ()
JsonArray ReadArray (JsonArray jsonArray)
JsonValue Parse ()
Private Attributes
TextScanner scanner
Detailed Description
Represents a reader that can read JsonValues.
Definition at line 13 of file JsonReader.cs.
Constructor & Destructor Documentation
LightJson.Serialization.JsonReader.JsonReader (TextReader reader) inline private
Definition at line 17 of file JsonReader.cs.
         {
             this.scanner = new TextScanner(reader);
         }
Member Function Documentation
JsonValue LightJson.Serialization.JsonReader.Parse () inline private
Definition at line 405 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.SkipWhitespace().
Referenced by LightJson.Serialization.JsonReader.Parse(), LightJson.JsonValue.Parse(), and LightJson.Serialization.JsonReader.ParseFile().
         {
             this.scanner.SkipWhitespace();
             return ReadJsonValue();
         }
static JsonValue LightJson.Serialization.JsonReader.Parse (TextReader reader) inline static
Creates a JsonValue by using the given TextReader.
Parameters
reader The TextReader used to read a JSON message.
Definition at line 415 of file JsonReader.cs.
References LightJson.Serialization.JsonReader.Parse().
         {
             if (reader == null)
             {
                 throw new ArgumentNullException("reader");
             }
             return new JsonReader(reader).Parse();
         }
static JsonValue LightJson.Serialization.JsonReader.Parse (string source) inline static
Creates a JsonValue by reader the JSON message in the given string.
Parameters
source The string containing the JSON message.
Definition at line 429 of file JsonReader.cs.
References LightJson.Serialization.JsonReader.Parse().
         {
             if (source == null)
             {
                 throw new ArgumentNullException("source");
             }
             using (var reader = new StringReader(source))
             {
                 return new JsonReader(reader).Parse();
             }
         }
static JsonValue LightJson.Serialization.JsonReader.ParseFile (string path) inline static
Creates a JsonValue by reading the given file.
Parameters
path The file path to be read.
Definition at line 446 of file JsonReader.cs.
References LightJson.Serialization.JsonReader.Parse().
Referenced by BGC.IO.FileReader.ReadJsonFile().
         {
             if (path == null)
             {
                 throw new ArgumentNullException("path");
             }
             using (var reader = new StreamReader(path))
             {
                 return new JsonReader(reader).Parse();
             }
         }
JsonArray LightJson.Serialization.JsonReader.ReadArray () inline private
Definition at line 355 of file JsonReader.cs.
         {
             return ReadArray(new JsonArray());
         }
JsonArray LightJson.Serialization.JsonReader.ReadArray (JsonArray jsonArray) inline private
Definition at line 360 of file JsonReader.cs.
References LightJson.JsonArray.Add(), LightJson.Serialization.TextScanner.Assert(), LightJson.Serialization.TextScanner.Peek(), LightJson.Serialization.TextScanner.Read(), and LightJson.Serialization.TextScanner.SkipWhitespace().
         {
             this.scanner.Assert('[');
             this.scanner.SkipWhitespace();
             if (this.scanner.Peek() == ']')
             {
                 this.scanner.Read();
             }
             else
             {
                 while (true)
                 {
                     this.scanner.SkipWhitespace();
                     var value = ReadJsonValue();
                     jsonArray.Add(value);
                     this.scanner.SkipWhitespace();
                     var next = this.scanner.Read();
                     if (next == ']')
                     {
                         break;
                     }
                     else if (next == ',')
                     {
                         continue;
                     }
                     else
                     {
                         throw new JsonParseException(
                             ErrorType.InvalidOrUnexpectedCharacter,
                             this.scanner.Position
                         );
                     }
                 }
             }
             return jsonArray;
         }
JsonValue LightJson.Serialization.JsonReader.ReadBoolean () inline private
Definition at line 73 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.Assert(), and LightJson.Serialization.TextScanner.Peek().
         {
             switch (this.scanner.Peek())
             {
                 case 't':
                     this.scanner.Assert("true");
                     return true;
                 case 'f':
                     this.scanner.Assert("false");
                     return false;
                 default:
                     throw new JsonParseException(
                         ErrorType.InvalidOrUnexpectedCharacter,
                         this.scanner.Position
                     );
             }
         }
void LightJson.Serialization.JsonReader.ReadDigits (StringBuilder builder) inline private
Definition at line 93 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.Peek(), and LightJson.Serialization.TextScanner.Read().
         {
             while (char.IsNumber(this.scanner.Peek()))
             {
                 builder.Append(this.scanner.Read());
             }
         }
int LightJson.Serialization.JsonReader.ReadHexDigit () inline private
Definition at line 217 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.Read().
         {
             switch (char.ToUpper(this.scanner.Read()))
             {
                 case '0':
                     return 0;
                 case '1':
                     return 1;
                 case '2':
                     return 2;
                 case '3':
                     return 3;
                 case '4':
                     return 4;
                 case '5':
                     return 5;
                 case '6':
                     return 6;
                 case '7':
                     return 7;
                 case '8':
                     return 8;
                 case '9':
                     return 9;
                 case 'A':
                     return 10;
                 case 'B':
                     return 11;
                 case 'C':
                     return 12;
                 case 'D':
                     return 13;
                 case 'E':
                     return 14;
                 case 'F':
                     return 15;
                 default:
                     throw new JsonParseException(
                         ErrorType.InvalidOrUnexpectedCharacter,
                         this.scanner.Position
                     );
             }
         }
string LightJson.Serialization.JsonReader.ReadJsonKey () inline private
Definition at line 22 of file JsonReader.cs.
         {
             return ReadString();
         }
JsonValue LightJson.Serialization.JsonReader.ReadJsonValue () inline private
Definition at line 27 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.Peek(), and LightJson.Serialization.TextScanner.SkipWhitespace().
         {
             this.scanner.SkipWhitespace();
             var next = this.scanner.Peek();
             if (char.IsNumber(next))
             {
                 return ReadNumber();
             }
             switch (next)
             {
                 case '{':
                     return ReadObject();
                 case '[':
                     return ReadArray();
                 case '"':
                     return ReadString();
                 case '-':
                     return ReadNumber();
                 case 't':
                 case 'f':
                     return ReadBoolean();
                 case 'n':
                     return ReadNull();
                 default:
                     throw new JsonParseException(
                         ErrorType.InvalidOrUnexpectedCharacter,
                         this.scanner.Position
                     );
             }
         }
JsonValue LightJson.Serialization.JsonReader.ReadNull () inline private
Definition at line 67 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.Assert(), and LightJson.JsonValue.Null.
         {
             this.scanner.Assert("null");
             return JsonValue.Null;
         }
JsonValue LightJson.Serialization.JsonReader.ReadNumber () inline private
Definition at line 101 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.Peek(), and LightJson.Serialization.TextScanner.Read().
         {
             var builder = new StringBuilder();
             if (this.scanner.Peek() == '-')
             {
                 builder.Append(this.scanner.Read());
             }
             if (this.scanner.Peek() == '0')
             {
                 builder.Append(this.scanner.Read());
             }
             else
             {
                 ReadDigits(builder);
             }
             if (this.scanner.Peek() == '.')
             {
                 builder.Append(this.scanner.Read());
                 ReadDigits(builder);
             }
             if (char.ToLower(this.scanner.Peek()) == 'e')
             {
                 builder.Append(this.scanner.Read());
                 var next = this.scanner.Peek();
                 switch (next)
                 {
                     case '+':
                     case '-':
                         builder.Append(this.scanner.Read());
                         break;
                 }
                 ReadDigits(builder);
             }
             return double.Parse(
                 builder.ToString(),
                 CultureInfo.InvariantCulture
             );
         }
JsonObject LightJson.Serialization.JsonReader.ReadObject () inline private
Definition at line 289 of file JsonReader.cs.
         {
             return ReadObject(new JsonObject());
         }
JsonObject LightJson.Serialization.JsonReader.ReadObject (JsonObject jsonObject) inline private
Definition at line 294 of file JsonReader.cs.
References LightJson.JsonObject.Add(), LightJson.Serialization.TextScanner.Assert(), LightJson.JsonObject.ContainsKey(), LightJson.Serialization.TextScanner.Peek(), LightJson.Serialization.TextScanner.Read(), and LightJson.Serialization.TextScanner.SkipWhitespace().
         {
             this.scanner.Assert('{');
             this.scanner.SkipWhitespace();
             if (this.scanner.Peek() == '}')
             {
                 this.scanner.Read();
             }
             else
             {
                 while (true)
                 {
                     this.scanner.SkipWhitespace();
                     var key = ReadJsonKey();
                     if (jsonObject.ContainsKey(key))
                     {
                         throw new JsonParseException(
                             ErrorType.DuplicateObjectKeys,
                             this.scanner.Position
                         );
                     }
                     this.scanner.SkipWhitespace();
                     this.scanner.Assert(':');
                     this.scanner.SkipWhitespace();
                     var value = ReadJsonValue();
                     jsonObject.Add(key, value);
                     this.scanner.SkipWhitespace();
                     var next = this.scanner.Read();
                     if (next == '}')
                     {
                         break;
                     }
                     else if (next == ',')
                     {
                         continue;
                     }
                     else
                     {
                         throw new JsonParseException(
                             ErrorType.InvalidOrUnexpectedCharacter,
                             this.scanner.Position
                         );
                     }
                 }
             }
             return jsonObject;
         }
string LightJson.Serialization.JsonReader.ReadString () inline private
Definition at line 148 of file JsonReader.cs.
References LightJson.Serialization.TextScanner.Assert(), and LightJson.Serialization.TextScanner.Read().
         {
             var builder = new StringBuilder();
             this.scanner.Assert('"');
             while (true)
             {
                 var c = this.scanner.Read();
                 if (c == '\\')
                 {
                     c = this.scanner.Read();
                     switch (char.ToLower(c))
                     {
                         case '"':  // "
                         case '\\': // \
                         case '/':  // /
                             builder.Append(c);
                             break;
                         case 'b':
                             builder.Append('\b');
                             break;
                         case 'f':
                             builder.Append('\f');
                             break;
                         case 'n':
                             builder.Append('\n');
                             break;
                         case 'r':
                             builder.Append('\r');
                             break;
                         case 't':
                             builder.Append('\t');
                             break;
                         case 'u':
                             builder.Append(ReadUnicodeLiteral());
                             break;
                         default:
                             throw new JsonParseException(
                                 ErrorType.InvalidOrUnexpectedCharacter,
                                 this.scanner.Position
                             );
                     }
                 }
                 else if (c == '"')
                 {
                     break;
                 }
                 else
                 {
                     if (char.IsControl(c))
                     {
                         throw new JsonParseException(
                             ErrorType.InvalidOrUnexpectedCharacter,
                             this.scanner.Position
                         );
                     }
                     else
                     {
                         builder.Append(c);
                     }
                 }
             }
             return builder.ToString();
         }
char LightJson.Serialization.JsonReader.ReadUnicodeLiteral () inline private
Definition at line 277 of file JsonReader.cs.
         {
             int value = 0;
             value += ReadHexDigit() * 4096; // 16^3
             value += ReadHexDigit() * 256;  // 16^2
             value += ReadHexDigit() * 16;   // 16^1
             value += ReadHexDigit();        // 16^0
             return (char)value;
         }
Field Documentation
TextScanner LightJson.Serialization.JsonReader.scanner private
Definition at line 15 of file JsonReader.cs.
The documentation for this class was generated from the following file:
LightJSON/Serialization/JsonReader.cs