BGC Tools: BGC.Web.AWSServer Class Reference
BGC.Web.AWSServer Class Reference
Data Structures
class BodyKeys
class HeaderKeys
Static Public Member Functions
static void PostFileToAWS (string filePath, string bucket, string serverPath, Action< UnityWebRequest > callBack=null)
static void PostToAWS (string fileContents, string bucket, string serverPath, Action< UnityWebRequest > callBack=null)
Post a string to Aws
static string Combine (string a, string b)
Combine two strings to form a path in AWS
Data Fields
const string PathSeparator = "/"
const string ApiUrl = "https://kukp0cevff.execute-api.us-east-2.amazonaws.com/prod/post_file_to_s3"
const string ApiKey = "eQtoU42BkJ697U9t74dQH73fjxdfcy7p70Rvs1Ft"
const string CacheControl = "no-cache"
const string BGCExtension = ".bgc"
Static Private Member Functions
static bool containsBGCExtension (string path)
Private Attributes
const char extensionSplitter = '.'
Detailed Description
Definition at line 11 of file AWSServer.cs.
Member Function Documentation
static string BGC.Web.AWSServer.Combine (string a, string b) inline static
Combine two strings to form a path in AWS
Parameters
str
Returns
a + "/" + b
Definition at line 110 of file AWSServer.cs.
Referenced by BGC.IO.Logging.Logger.CloseFile(), and BGC.Utility.LogFilesTos3.migrateUser().
         {
             return a + PathSeparator + b;
         }
static bool BGC.Web.AWSServer.containsBGCExtension (string path) inline static private
Definition at line 115 of file AWSServer.cs.
         {
             return Path.HasExtension(BGCExtension);
         }
static void BGC.Web.AWSServer.PostFileToAWS (string filePath, string bucket, string serverPath, Action< UnityWebRequest > callBack = null) inline static
Definition at line 34 of file AWSServer.cs.
Referenced by BGC.IO.Logging.Logger.CloseFile(), and BGC.Utility.LogFilesTos3.migrateUser().
         {
             if (File.Exists(filePath) == false)
             {
                 Debug.LogError(filePath + " is not a file.");
                 callBack?.Invoke(null);
                 return;
             }
             if (containsBGCExtension(filePath) == false)
             {
                 Debug.LogError("file " + filePath + " must have the bgc extension.");
                 callBack?.Invoke(null);
                 return;
             }
             StreamReader reader = new StreamReader(filePath);
             string content = reader.ReadToEnd();
             reader.Close();
             PostToAWS(
                 content,
                 bucket,
                 serverPath,
                 callBack);
         }
static void BGC.Web.AWSServer.PostToAWS (string fileContents, string bucket, string serverPath, Action< UnityWebRequest > callBack = null) inline static
Post a string to Aws
Parameters
url
bucket
serverPath
fileContents
callBack True means there was an error
Definition at line 75 of file AWSServer.cs.
References LightJson.JsonObject.Add(), BGC.Web.AWSServer.HeaderKeys.ApiKey, BGC.Web.AWSServer.BodyKeys.Bucket, BGC.Web.AWSServer.HeaderKeys.CacheControl, BGC.Web.AWSServer.BodyKeys.Content, BGC.Web.AWSServer.BodyKeys.Path, BGC.Web.Utility.Rest.PostRequest(), and LightJson.JsonObject.ToString().
         {
             if (containsBGCExtension(serverPath) == false)
             {
                 Debug.LogError("server path " + serverPath + " must have a bgc extension \".bgc\"");
                 callBack?.Invoke(null);
                 return;
             }
             Dictionary<string, string> headers = new Dictionary<string, string>();
             headers.Add(HeaderKeys.ApiKey, ApiKey);
             headers.Add(HeaderKeys.CacheControl, CacheControl);
             JsonObject body = new JsonObject();
             body.Add(BodyKeys.Bucket, bucket);
             body.Add(BodyKeys.Path, serverPath);
             body.Add(BodyKeys.Content, fileContents);
             Rest.PostRequest(
                 ApiUrl,
                 headers,
                 body.ToString(),
                 callBack);
         }
Field Documentation
const string BGC.Web.AWSServer.ApiKey = "eQtoU42BkJ697U9t74dQH73fjxdfcy7p70Rvs1Ft"
Definition at line 28 of file AWSServer.cs.
const string BGC.Web.AWSServer.ApiUrl = "https://kukp0cevff.execute-api.us-east-2.amazonaws.com/prod/post_file_to_s3"
Definition at line 27 of file AWSServer.cs.
const string BGC.Web.AWSServer.BGCExtension = ".bgc"
Definition at line 30 of file AWSServer.cs.
const string BGC.Web.AWSServer.CacheControl = "no-cache"
Definition at line 29 of file AWSServer.cs.
const char BGC.Web.AWSServer.extensionSplitter = '.' private
Definition at line 32 of file AWSServer.cs.
const string BGC.Web.AWSServer.PathSeparator = "/"
Definition at line 26 of file AWSServer.cs.
The documentation for this class was generated from the following file:
Web/AWSServer.cs