BGC Tools: LightJson.Serialization.TextScanner Class Reference
LightJson.Serialization.TextScanner Class Reference
Represents a text scanner that reads one character at a time.
Public Member Functions
TextScanner (TextReader reader)
Initializes a new instance of TextScanner.
char Peek ()
Reads the next character in the stream without changing the current position.
char Read ()
Reads the next character in the stream, advancing the text position.
void SkipWhitespace ()
Advances the scanner to next non-whitespace character.
void Assert (char next)
Verifies that the given character matches the next character in the stream. If the characters do not match, an exception will be thrown.
void Assert (string next)
Verifies that the given string matches the next characters in the stream. If the strings do not match, an exception will be thrown.
Properties
TextPosition Position [get]
Gets the position of the scanner within the text.
Private Attributes
TextReader reader
TextPosition position
Detailed Description
Represents a text scanner that reads one character at a time.
Definition at line 12 of file TextScanner.cs.
Constructor & Destructor Documentation
LightJson.Serialization.TextScanner.TextScanner (TextReader reader) inline
Initializes a new instance of TextScanner.
Parameters
reader The TextReader to read the text.
Definition at line 32 of file TextScanner.cs.
         {
             this.reader = reader;
         }
Member Function Documentation
void LightJson.Serialization.TextScanner.Assert (char next) inline
Verifies that the given character matches the next character in the stream. If the characters do not match, an exception will be thrown.
Parameters
next The expected character.
Definition at line 103 of file TextScanner.cs.
Referenced by LightJson.Serialization.JsonReader.ReadArray(), LightJson.Serialization.JsonReader.ReadBoolean(), LightJson.Serialization.JsonReader.ReadNull(), LightJson.Serialization.JsonReader.ReadObject(), and LightJson.Serialization.JsonReader.ReadString().
         {
             if (Read() != next)
             {
                 throw new JsonParseException(
                     string.Format("Parser expected '{0}'", next),
                     ErrorType.InvalidOrUnexpectedCharacter,
                     this.position
                 );
             }
         }
void LightJson.Serialization.TextScanner.Assert (string next) inline
Verifies that the given string matches the next characters in the stream. If the strings do not match, an exception will be thrown.
Parameters
next The expected string.
Definition at line 120 of file TextScanner.cs.
         {
             for (var i = 0; i < next.Length; i += 1)
             {
                 Assert(next[i]);
             }
         }
char LightJson.Serialization.TextScanner.Peek () inline
Reads the next character in the stream without changing the current position.
Definition at line 40 of file TextScanner.cs.
Referenced by LightJson.Serialization.JsonReader.ReadArray(), LightJson.Serialization.JsonReader.ReadBoolean(), LightJson.Serialization.JsonReader.ReadDigits(), LightJson.Serialization.JsonReader.ReadJsonValue(), LightJson.Serialization.JsonReader.ReadNumber(), and LightJson.Serialization.JsonReader.ReadObject().
         {
             var next = reader.Peek();
             if (next == -1)
             {
                 throw new JsonParseException(
                     ErrorType.IncompleteMessage,
                     this.position
                 );
             }
             else
             {
                 return (char)next;
             }
         }
char LightJson.Serialization.TextScanner.Read () inline
Reads the next character in the stream, advancing the text position.
Definition at line 60 of file TextScanner.cs.
References LightJson.Serialization.TextPosition.column, and LightJson.Serialization.TextPosition.line.
Referenced by LightJson.Serialization.JsonReader.ReadArray(), LightJson.Serialization.JsonReader.ReadDigits(), LightJson.Serialization.JsonReader.ReadHexDigit(), LightJson.Serialization.JsonReader.ReadNumber(), LightJson.Serialization.JsonReader.ReadObject(), and LightJson.Serialization.JsonReader.ReadString().
         {
             var next = reader.Read();
             if (next == -1)
             {
                 throw new JsonParseException(
                     ErrorType.IncompleteMessage,
                     this.position
                 );
             }
             else
             {
                 if (next == '\n')
                 {
                     this.position.line += 1;
                     this.position.column = 0;
                 }
                 else
                 {
                     this.position.column += 1;
                 }
                 return (char)next;
             }
         }
void LightJson.Serialization.TextScanner.SkipWhitespace () inline
Advances the scanner to next non-whitespace character.
Definition at line 90 of file TextScanner.cs.
Referenced by LightJson.Serialization.JsonReader.Parse(), LightJson.Serialization.JsonReader.ReadArray(), LightJson.Serialization.JsonReader.ReadJsonValue(), and LightJson.Serialization.JsonReader.ReadObject().
         {
             while (char.IsWhiteSpace(Peek()))
             {
                 Read();
             }
         }
Field Documentation
TextPosition LightJson.Serialization.TextScanner.position private
Definition at line 15 of file TextScanner.cs.
TextReader LightJson.Serialization.TextScanner.reader private
Definition at line 14 of file TextScanner.cs.
Property Documentation
TextPosition LightJson.Serialization.TextScanner.Position get
Gets the position of the scanner within the text.
Definition at line 21 of file TextScanner.cs.
The documentation for this class was generated from the following file:
LightJSON/Serialization/TextScanner.cs