BGC Tools: LightJson.JsonValue Struct Reference
LightJson.JsonValue Struct Reference
A wrapper object that contains a valid JSON value.
Data Structures
class JsonValueDebugView
Public Member Functions
JsonValue (bool?value)
Initializes a new instance of the JsonValue struct, representing a Boolean value.
JsonValue (double?value)
Initializes a new instance of the JsonValue struct, representing a Number value.
JsonValue (string value)
Initializes a new instance of the JsonValue struct, representing a String value.
JsonValue (JsonObject value)
Initializes a new instance of the JsonValue struct, representing a JsonObject.
JsonValue (JsonArray value)
Initializes a new instance of the JsonValue struct, representing a Array reference value.
override bool Equals (object obj)
Returns a value indicating whether this JsonValue is equal to the given object.
override int GetHashCode ()
Returns a hash code for this JsonValue.
override string ToString ()
Returns a JSON string representing the state of the object.
string ToString (bool pretty)
Returns a JSON string representing the state of the object.
Static Public Member Functions
static implicit operator JsonValue (bool?value)
Converts the given nullable boolean into a JsonValue.
static implicit operator JsonValue (double?value)
Converts the given nullable double into a JsonValue.
static implicit operator JsonValue (string value)
Converts the given string into a JsonValue.
static implicit operator JsonValue (JsonObject value)
Converts the given JsonObject into a JsonValue.
static implicit operator JsonValue (JsonArray value)
Converts the given JsonArray into a JsonValue.
static implicit operator JsonValue (DateTime?value)
Converts the given DateTime? into a JsonValue.
static implicit operator int (JsonValue jsonValue)
Converts the given JsonValue into an Int.
static implicit operator int? (JsonValue jsonValue)
Converts the given JsonValue into a nullable Int.
static implicit operator bool (JsonValue jsonValue)
Converts the given JsonValue into a Bool.
static implicit operator bool? (JsonValue jsonValue)
Converts the given JsonValue into a nullable Bool.
static implicit operator double (JsonValue jsonValue)
Converts the given JsonValue into a Double.
static implicit operator double? (JsonValue jsonValue)
Converts the given JsonValue into a nullable Double.
static implicit operator string (JsonValue jsonValue)
Converts the given JsonValue into a String.
static implicit operator JsonObject (JsonValue jsonValue)
Converts the given JsonValue into a JsonObject.
static implicit operator JsonArray (JsonValue jsonValue)
Converts the given JsonValue into a JsonArray.
static implicit operator DateTime (JsonValue jsonValue)
Converts the given JsonValue into a DateTime.
static implicit operator DateTime? (JsonValue jsonValue)
Converts the given JsonValue into a nullable DateTime.
static bool operator== (JsonValue a, JsonValue b)
Returns a value indicating whether the two given JsonValues are equal.
static bool operator!= (JsonValue a, JsonValue b)
Returns a value indicating whether the two given JsonValues are unequal.
static JsonValue Parse (string text)
Returns a JsonValue by parsing the given string.
Static Public Attributes
static readonly JsonValue Null = new JsonValue(JsonValueType.Null, default(double), null)
Represents a null JsonValue.
Properties
JsonValueType Type [get]
Gets the type of this JsonValue.
bool IsNull [get]
Gets a value indicating whether this JsonValue is Null.
bool IsBoolean [get]
Gets a value indicating whether this JsonValue is a Boolean.
bool IsInteger [get]
Gets a value indicating whether this JsonValue is an Integer.
bool IsNumber [get]
Gets a value indicating whether this JsonValue is a Number.
bool IsString [get]
Gets a value indicating whether this JsonValue is a String.
bool IsJsonObject [get]
Gets a value indicating whether this JsonValue is a JsonObject.
bool IsJsonArray [get]
Gets a value indicating whether this JsonValue is a JsonArray.
bool IsDateTime [get]
Gets a value indicating whether this JsonValue represents a DateTime.
bool AsBoolean [get]
Gets this value as a Boolean type.
int AsInteger [get]
Gets this value as an Integer type.
double AsNumber [get]
Gets this value as a Number type.
string AsString [get]
Gets this value as a String type.
JsonObject AsJsonObject [get]
Gets this value as an JsonObject.
JsonArray AsJsonArray [get]
Gets this value as an JsonArray.
DateTime AsDateTime [get]
Gets this value as a system.DateTime.
object AsObject [get]
Gets this (inner) value as a System.object.
JsonValue this[string key] [get, set]
Gets or sets the value associated with the specified key.
JsonValue this[int index] [get, set]
Gets or sets the value at the specified index.
Private Member Functions
JsonValue (JsonValueType type, double value, object reference)
Initializes a new instance of the JsonValue struct.
Private Attributes
readonly JsonValueType type
readonly object reference
readonly double value
Detailed Description
A wrapper object that contains a valid JSON value.
Definition at line 12 of file JsonValue.cs.
Constructor & Destructor Documentation
LightJson.JsonValue.JsonValue (JsonValueType type, double value, object reference) inline private
Initializes a new instance of the JsonValue struct.
Parameters
type The Json type of the JsonValue.
value The internal value of the JsonValue. This is used when the Json type is Number or Boolean.
reference The internal value reference of the JsonValue. This value is used when the Json type is String, JsonObject, or JsonArray.
Definition at line 395 of file JsonValue.cs.
References LightJson.JsonValue.reference, LightJson.JsonValue.type, and LightJson.JsonValue.value.
Referenced by LightJson.JsonValue.operator JsonValue().
         {
             this.type      = type;
             this.value     = value;
             this.reference = reference;
         }
LightJson.JsonValue.JsonValue (bool? value) inline
Initializes a new instance of the JsonValue struct, representing a Boolean value.
Parameters
value The value to be wrapped.
Definition at line 406 of file JsonValue.cs.
References LightJson.JsonValue.Null.
         {
             if (value.HasValue)
             {
                 this.reference = null;
                 this.type = JsonValueType.Boolean;
                 this.value = value.Value ? 1 : 0;
             }
             else
             {
                 this = JsonValue.Null;
             }
         }
LightJson.JsonValue.JsonValue (double? value) inline
Initializes a new instance of the JsonValue struct, representing a Number value.
Parameters
value The value to be wrapped.
Definition at line 426 of file JsonValue.cs.
References LightJson.JsonValue.Null.
         {
             if (value.HasValue)
             {
                 this.reference = null;
                 this.type = JsonValueType.Number;
                 this.value = value.Value;
             }
             else
             {
                 this = JsonValue.Null;
             }
         }
LightJson.JsonValue.JsonValue (string value) inline
Initializes a new instance of the JsonValue struct, representing a String value.
Parameters
value The value to be wrapped.
Definition at line 446 of file JsonValue.cs.
References LightJson.JsonValue.Null, and LightJson.JsonValue.value.
         {
             if (value != null)
             {
                 this.value = default(double);
                 this.type = JsonValueType.String;
                 this.reference = value;
             }
             else
             {
                 this = JsonValue.Null;
             }
         }
LightJson.JsonValue.JsonValue (JsonObject value) inline
Initializes a new instance of the JsonValue struct, representing a JsonObject.
Parameters
value The value to be wrapped.
Definition at line 466 of file JsonValue.cs.
References LightJson.JsonValue.Null, and LightJson.JsonValue.value.
         {
             if (value != null)
             {
                 this.value = default(double);
                 this.type = JsonValueType.Object;
                 this.reference = value;
             }
             else
             {
                 this = JsonValue.Null;
             }
         }
LightJson.JsonValue.JsonValue (JsonArray value) inline
Initializes a new instance of the JsonValue struct, representing a Array reference value.
Parameters
value The value to be wrapped.
Definition at line 486 of file JsonValue.cs.
References LightJson.JsonValue.Null, and LightJson.JsonValue.value.
         {
             if (value != null)
             {
                 this.value = default(double);
                 this.type = JsonValueType.Array;
                 this.reference = value;
             }
             else
             {
                 this = JsonValue.Null;
             }
         }
Member Function Documentation
override bool LightJson.JsonValue.Equals (object obj) inline
Returns a value indicating whether this JsonValue is equal to the given object.
Parameters
obj The object to test.
Definition at line 790 of file JsonValue.cs.
References LightJson.JsonValue.IsNull.
Referenced by LightJson.JsonValue.operator==().
         {
             var jsonValue = obj as JsonValue?;
             if (jsonValue == null)
             {
                 return this.IsNull;
             }
             else
             {
                 return (this == jsonValue.Value);
             }
         }
override int LightJson.JsonValue.GetHashCode () inline
Returns a hash code for this JsonValue.
Definition at line 807 of file JsonValue.cs.
References LightJson.JsonValue.IsNull, and LightJson.JsonValue.Type.
         {
             if (this.IsNull)
             {
                 return this.Type.GetHashCode();
             }
             else
             {
                 return this.Type.GetHashCode()
                     ^ this.value.GetHashCode()
                     ^ this.reference.GetHashCode();
             }
         }
static implicit LightJson.JsonValue.operator bool (JsonValue jsonValue) inline static
Converts the given JsonValue into a Bool.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 605 of file JsonValue.cs.
References LightJson.JsonValue.IsBoolean, and LightJson.JsonValue.value.
         {
             if (jsonValue.IsBoolean)
             {
                 return (jsonValue.value == 1);
             }
             else
             {
                 return false;
             }
         }
static implicit LightJson.JsonValue.operator bool? (JsonValue jsonValue) inline static
Converts the given JsonValue into a nullable Bool.
Parameters
jsonValue The JsonValue to be converted.
Exceptions
System.InvalidCastException Throws System.InvalidCastException when the inner value type of the JsonValue is not the desired type of the conversion.
Definition at line 625 of file JsonValue.cs.
         {
             if (jsonValue.IsNull)
             {
                 return null;
             }
             else
             {
                 return (bool)jsonValue;
             }
         }
static implicit LightJson.JsonValue.operator DateTime (JsonValue jsonValue) inline static
Converts the given JsonValue into a DateTime.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 725 of file JsonValue.cs.
References LightJson.JsonValue.AsDateTime.
         {
             var dateTime = jsonValue.AsDateTime;
             if (dateTime.HasValue)
             {
                 return dateTime.Value;
             }
             else
             {
                 return DateTime.MinValue;
             }
         }
static implicit LightJson.JsonValue.operator DateTime? (JsonValue jsonValue) inline static
Converts the given JsonValue into a nullable DateTime.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 743 of file JsonValue.cs.
         {
             if (jsonValue.IsDateTime || jsonValue.IsNull)
             {
                 return jsonValue.AsDateTime;
             }
             else
             {
                 return null;
             }
         }
static implicit LightJson.JsonValue.operator double (JsonValue jsonValue) inline static
Converts the given JsonValue into a Double.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 641 of file JsonValue.cs.
References LightJson.JsonValue.IsNumber, and LightJson.JsonValue.value.
         {
             if (jsonValue.IsNumber)
             {
                 return jsonValue.value;
             }
             else
             {
                 return double.NaN;
             }
         }
static implicit LightJson.JsonValue.operator double? (JsonValue jsonValue) inline static
Converts the given JsonValue into a nullable Double.
Parameters
jsonValue The JsonValue to be converted.
Exceptions
System.InvalidCastException Throws System.InvalidCastException when the inner value type of the JsonValue is not the desired type of the conversion.
Definition at line 661 of file JsonValue.cs.
         {
             if (jsonValue.IsNull)
             {
                 return null;
             }
             else
             {
                 return (double)jsonValue;
             }
         }
static implicit LightJson.JsonValue.operator int (JsonValue jsonValue) inline static
Converts the given JsonValue into an Int.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 569 of file JsonValue.cs.
References LightJson.JsonValue.AsInteger, and LightJson.JsonValue.IsInteger.
         {
             if (jsonValue.IsInteger)
             {
                 return jsonValue.AsInteger;
             }
             else
             {
                 return 0;
             }
         }
static implicit LightJson.JsonValue.operator int? (JsonValue jsonValue) inline static
Converts the given JsonValue into a nullable Int.
Parameters
jsonValue The JsonValue to be converted.
Exceptions
System.InvalidCastException Throws System.InvalidCastException when the inner value type of the JsonValue is not the desired type of the conversion.
Definition at line 589 of file JsonValue.cs.
         {
             if (jsonValue.IsNull)
             {
                 return null;
             }
             else
             {
                 return (int)jsonValue;
             }
         }
static implicit LightJson.JsonValue.operator JsonArray (JsonValue jsonValue) inline static
Converts the given JsonValue into a JsonArray.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 709 of file JsonValue.cs.
References LightJson.JsonValue.IsJsonArray, LightJson.JsonValue.IsNull, and LightJson.JsonValue.reference.
         {
             if (jsonValue.IsJsonArray || jsonValue.IsNull)
             {
                 return jsonValue.reference as JsonArray;
             }
             else
             {
                 return null;
             }
         }
static implicit LightJson.JsonValue.operator JsonObject (JsonValue jsonValue) inline static
Converts the given JsonValue into a JsonObject.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 693 of file JsonValue.cs.
References LightJson.JsonValue.IsJsonObject, LightJson.JsonValue.IsNull, and LightJson.JsonValue.reference.
         {
             if (jsonValue.IsJsonObject || jsonValue.IsNull)
             {
                 return jsonValue.reference as JsonObject;
             }
             else
             {
                 return null;
             }
         }
static implicit LightJson.JsonValue.operator JsonValue (bool? value) inline static
Converts the given nullable boolean into a JsonValue.
Parameters
value The value to be converted.
Definition at line 506 of file JsonValue.cs.
References LightJson.JsonValue.JsonValue().
         {
             return new JsonValue(value);
         }
static implicit LightJson.JsonValue.operator JsonValue (double? value) inline static
Converts the given nullable double into a JsonValue.
Parameters
value The value to be converted.
Definition at line 515 of file JsonValue.cs.
References LightJson.JsonValue.JsonValue().
         {
             return new JsonValue(value);
         }
static implicit LightJson.JsonValue.operator JsonValue (string value) inline static
Converts the given string into a JsonValue.
Parameters
value The value to be converted.
Definition at line 524 of file JsonValue.cs.
References LightJson.JsonValue.JsonValue().
         {
             return new JsonValue(value);
         }
static implicit LightJson.JsonValue.operator JsonValue (JsonObject value) inline static
Converts the given JsonObject into a JsonValue.
Parameters
value The value to be converted.
Definition at line 533 of file JsonValue.cs.
References LightJson.JsonValue.JsonValue().
         {
             return new JsonValue(value);
         }
static implicit LightJson.JsonValue.operator JsonValue (JsonArray value) inline static
Converts the given JsonArray into a JsonValue.
Parameters
value The value to be converted.
Definition at line 542 of file JsonValue.cs.
References LightJson.JsonValue.JsonValue().
         {
             return new JsonValue(value);
         }
static implicit LightJson.JsonValue.operator JsonValue (DateTime? value) inline static
Converts the given DateTime? into a JsonValue.
The DateTime value will be stored as a string using ISO 8601 format, since JSON does not define a DateTime type.
Parameters
value The value to be converted.
Definition at line 555 of file JsonValue.cs.
References LightJson.JsonValue.JsonValue(), and LightJson.JsonValue.Null.
         {
             if (value == null)
             {
                 return JsonValue.Null;
             }
             return new JsonValue(value.Value.ToString("o"));
         }
static implicit LightJson.JsonValue.operator string (JsonValue jsonValue) inline static
Converts the given JsonValue into a String.
Parameters
jsonValue The JsonValue to be converted.
Definition at line 677 of file JsonValue.cs.
References LightJson.JsonValue.IsNull, LightJson.JsonValue.IsString, and LightJson.JsonValue.reference.
         {
             if (jsonValue.IsString || jsonValue.IsNull)
             {
                 return jsonValue.reference as string;
             }
             else
             {
                 return null;
             }
         }
static bool LightJson.JsonValue.operator!= (JsonValue a, JsonValue b) inline static
Returns a value indicating whether the two given JsonValues are unequal.
Parameters
a A JsonValue to compare.
b A JsonValue to compare.
Definition at line 772 of file JsonValue.cs.
         {
             return !(a == b);
         }
static bool LightJson.JsonValue.operator== (JsonValue a, JsonValue b) inline static
Returns a value indicating whether the two given JsonValues are equal.
Parameters
a A JsonValue to compare.
b A JsonValue to compare.
Definition at line 760 of file JsonValue.cs.
References LightJson.JsonValue.Equals(), LightJson.JsonValue.reference, LightJson.JsonValue.Type, and LightJson.JsonValue.value.
         {
             return (a.Type == b.Type)
                 && (a.value == b.value)
                 && Equals(a.reference, b.reference);
         }
static JsonValue LightJson.JsonValue.Parse (string text) inline static
Returns a JsonValue by parsing the given string.
Parameters
text The JSON-formatted string to be parsed.
Definition at line 781 of file JsonValue.cs.
References LightJson.Serialization.JsonReader.Parse().
         {
             return JsonReader.Parse(text);
         }
override string LightJson.JsonValue.ToString () inline
Returns a JSON string representing the state of the object.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Definition at line 828 of file JsonValue.cs.
         {
             return ToString(false);
         }
string LightJson.JsonValue.ToString (bool pretty) inline
Returns a JSON string representing the state of the object.
The resulting string is safe to be inserted as is into dynamically generated JavaScript or JSON code.
Parameters
pretty Indicates whether the resulting string should be formatted for human-readability.
Definition at line 843 of file JsonValue.cs.
         {
             using (var reader = new JsonWriter(pretty))
             {
                 return reader.Serialize(this);
             }
         }
Field Documentation
readonly JsonValue LightJson.JsonValue.Null = new JsonValue(JsonValueType.Null, default(double), null) static
Represents a null JsonValue.
Definition at line 21 of file JsonValue.cs.
Referenced by LightJson.JsonObject.Add(), LightJson.JsonValue.JsonValue(), LightJson.JsonValue.operator JsonValue(), and LightJson.Serialization.JsonReader.ReadNull().
readonly object LightJson.JsonValue.reference private
Definition at line 15 of file JsonValue.cs.
Referenced by LightJson.JsonValue.JsonValue(), LightJson.JsonValue.operator JsonArray(), LightJson.JsonValue.operator JsonObject(), LightJson.JsonValue.operator string(), and LightJson.JsonValue.operator==().
readonly JsonValueType LightJson.JsonValue.type private
Definition at line 14 of file JsonValue.cs.
Referenced by LightJson.JsonValue.JsonValue().
readonly double LightJson.JsonValue.value private
Definition at line 16 of file JsonValue.cs.
Referenced by LightJson.JsonValue.JsonValue(), LightJson.JsonValue.operator bool(), LightJson.JsonValue.operator double(), and LightJson.JsonValue.operator==().
Property Documentation
bool LightJson.JsonValue.AsBoolean get
Gets this value as a Boolean type.
Definition at line 140 of file JsonValue.cs.
DateTime LightJson.JsonValue.AsDateTime get
Gets this value as a system.DateTime.
Definition at line 277 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator DateTime().
int LightJson.JsonValue.AsInteger get
Gets this value as an Integer type.
Definition at line 168 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator int().
JsonArray LightJson.JsonValue.AsJsonArray get
Gets this value as an JsonArray.
Definition at line 264 of file JsonValue.cs.
JsonObject LightJson.JsonValue.AsJsonObject get
Gets this value as an JsonObject.
Definition at line 251 of file JsonValue.cs.
double LightJson.JsonValue.AsNumber get
Gets this value as a Number type.
Definition at line 191 of file JsonValue.cs.
object LightJson.JsonValue.AsObject get
Gets this (inner) value as a System.object.
Definition at line 297 of file JsonValue.cs.
string LightJson.JsonValue.AsString get
Gets this value as a String type.
Definition at line 225 of file JsonValue.cs.
Referenced by LightJson.Serialization.JsonWriter.WriteEncodedJsonValue().
bool LightJson.JsonValue.IsBoolean get
Gets a value indicating whether this JsonValue is a Boolean.
Definition at line 49 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator bool().
bool LightJson.JsonValue.IsDateTime get
Gets a value indicating whether this JsonValue represents a DateTime.
Definition at line 129 of file JsonValue.cs.
bool LightJson.JsonValue.IsInteger get
Gets a value indicating whether this JsonValue is an Integer.
Definition at line 60 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator int().
bool LightJson.JsonValue.IsJsonArray get
Gets a value indicating whether this JsonValue is a JsonArray.
Definition at line 118 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator JsonArray().
bool LightJson.JsonValue.IsJsonObject get
Gets a value indicating whether this JsonValue is a JsonObject.
Definition at line 107 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator JsonObject().
bool LightJson.JsonValue.IsNull get
Gets a value indicating whether this JsonValue is Null.
Definition at line 38 of file JsonValue.cs.
Referenced by LightJson.JsonValue.Equals(), LightJson.JsonValue.GetHashCode(), LightJson.JsonValue.operator JsonArray(), LightJson.JsonValue.operator JsonObject(), and LightJson.JsonValue.operator string().
bool LightJson.JsonValue.IsNumber get
Gets a value indicating whether this JsonValue is a Number.
Definition at line 85 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator double().
bool LightJson.JsonValue.IsString get
Gets a value indicating whether this JsonValue is a String.
Definition at line 96 of file JsonValue.cs.
Referenced by LightJson.JsonValue.operator string().
JsonValue LightJson.JsonValue.this[int index] get set
Gets or sets the value at the specified index.
Parameters
index The zero-based index of the value to get or set.
Exceptions
System.InvalidOperationException Thrown when this JsonValue is not a JsonArray
Definition at line 358 of file JsonValue.cs.
JsonValue LightJson.JsonValue.this[string key] get set
Gets or sets the value associated with the specified key.
Parameters
key The key of the value to get or set.
Exceptions
System.InvalidOperationException Thrown when this JsonValue is not a JsonObject.
Definition at line 325 of file JsonValue.cs.
JsonValueType LightJson.JsonValue.Type get
Gets the type of this JsonValue.
Definition at line 27 of file JsonValue.cs.
Referenced by LightJson.JsonValue.GetHashCode(), LightJson.JsonValue.operator==(), LightJson.Serialization.JsonWriter.Render(), and LightJson.Serialization.JsonWriter.WriteEncodedJsonValue().
The documentation for this struct was generated from the following file:
LightJSON/JsonValue.cs